### ISSUE TITLE
Fix for: Date/Time Fields in Fiori Elements with CAP and OData V2 Proxy are not displayed

### ISSUE THREAD

**Issue by oklemenz2** [marianfoo/ui5-cc-excelUpload-sampleapp#1]
As written in my answer to your question here:
https://answers.sap.com/questions/13772441/datetime-fields-in-fiori-elements-with-cap-and-oda.html?childToView=13772501
here are some delta changes to your project, to get it working with unmanaged compositions.

Files: [project.zip](https://github.com/marianfoo/ui5-cc-excelUpload-sampleapp/files/10198110/project.zip)

**Comment by marianfoo** [comment]
fixed with https://github.com/marianfoo/ui5-cc-excelUpload-sampleapp/commit/22640bb475e42e48ec3824bf524dbe20dd7e7d6d
